### ISSUE TITLE
Using AIC and BIC for Model Selection does not work in 0.2.8 ?

### ISSUE THREAD

**Issue by carstenf** [hmmlearn/hmmlearn#511]
## I am reporting a bug

- Make sure that it occurs with the latest release of hmmlearn (per
  https://pypi.org/project/hmmlearn/). -> re-installed everything new, version ia now 0.2.8

- im running the following example:
https://hmmlearn.readthedocs.io/en/latest/auto_examples/plot_gaussian_model_selection.html

- I get the following error:  'GaussianHMM' object has no attribute 'aic'

it looks like the aic and bic are not implemented yet?

**Comment by blckmaxima** [comment]
I think this is only implemented on the HEAD, try using the latest from
GitHub please.

**Comment by carstenf** [comment]
Thanks, now I tried

 pip install --user git+https://github.com/hmmlearn/hmmlearn 
(after:  pip uninstall hmmlearn  --yes   )

Same outcome

Some other ideas?

Thanks

**Comment by blckmaxima** [comment]
Can you make sure you don't have any other versions installed elsewhere?  I
just tested this in a virtual-environment and it found the aic/bic member
methods.

Doing and "import hmmlearn; print(hmmlearn)"  will show you if you are
picking up the most recent version you installed.

**Comment by carstenf** [comment]
Just tested it with a new environment and it works fine.
need to fine out why it does not work with my usually one....

Thankx for checking! 
I'm closing this
